language: node_js 
node_js:
  - 12  # 使用 nodejs LTS v10
branches:
  only:
    - source # 只监控 source 的 branch
cache:
  directories:
    - node_modules # 缓存 node_modules 加快构建速度
before_install:
    - export TZ='Asia/Shanghai'    
before_script: ## 根据你所用的主题和自定义的不同，这里会有所不同
  - npm install -g hexo-cli # 在 CI 环境内安装 Hexo
  # - git clone https://github.com/next-theme/hexo-theme-next themes/next #从 Github 上拉取 Suka 主题
  # - cd themes/next
  # - npm install --production # 安装 Suka 主题的依赖
  # - cd ../.. # 返回站点根目录
  - npm install # 在根目录安装站点需要的依赖 
script: 
  - hexo clean
  - hexo generate # generate static files
deploy: # 根据个人情况，这里会有所不同
  provider: pages
  skip_cleanup: true # 构建完成后不清除
  token: $GH_TOKEN # 你刚刚设置的 token
  keep_history: true # 保存历史
  fqdn: koukoustar.cn # 自定义域名，使用 username.github.io 可删除
  on:
    branch: source # hexo 站点源文件所在的 branch
  local_dir: public 
  target_branch: gh-pages # 存放生成站点文件的 branch，使用 username.github.io 必须是 master


env:
    global:
        - GH_REF: github.com/wangpei72/wangpei72.github.io.git #设置GH_REF，注意更改yourname
