# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Welcome to koukouStar's Blog
subtitle: ''
description: ''
keywords:
author: koukoustar
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://koukoustar.cn
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# markdown:
##  plugins:
##    - hexo-math

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:wangpei72/wangpei72.github.io
  branch: gh-pages

search:
  path: search.xml
  field: post
  content: true
  format: html

theme_config:
  social:
    GitHub: https://github.com/wangpei72 || fab fa-github
    E-Mail: mailto:wpkkstr@gmail.com || fa fa-envelope
    Weibo: https://weibo.com/u/6624315543 || fab fa-weibo
    Google: https://plus.google.com/wpkkstr || fab fa-google
    Twitter: https://twitter.com/koukoustar3 || fab fa-twitter
    FB Page: https://www.facebook.com/pei.wang.1466126 || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    # YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype  
  avatar:
    # Replace the default image and set the url here.
    url: /images/avatar.gif
    # If true, the avatar will be dispalyed in circle.
    rounded: false
    # If true, the avatar will be rotated with the cursor.
    rotated: true
  # scheme: Muse
  scheme: Mist
  # scheme: Pisces
  # scheme: Gemini
  language: zh-Hans
  menu:
  home: / 
  #about: /about/ || fa fa-user
  tags: /tags/ 
  #categories: /categories/ || fa fa-th
  archives: /archives/ 
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

  menu_settings:
    icons: true
    badges: false
  sidebar:
    display: post
  baidu_analytics: ecb87535d9cf17e94cd6ba19cd63b06f    

  leancloud_visitors:
    enable: true
    app_id: hpvFBiv00KI5T4MJlJ0X4kGs-9Nh9j0Va
    app_key: NM6BCuXqe6i2mac04S6y733a
    # Required for apps from CN region
    server_url: # <your server url>
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in leancloud counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
    security: false

  footer:  
    since: 2021
    icon:
    # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: star
      # If you want to animate the icon, set it to true.
      animated: false
      # Change the color of icon, using Hex Code.
      color: "#ff0000"
    # If not defined, `author` from Hexo `_config.yml` will be used.
    copyright: koukoustar
    powered: true
    
  
  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: true
      another_day: true
    categories: true